- name: init_limx_jdk
  hosts: all
  sudo: True
  tasks:
    - name: init_limx_src_dir
      file:
        state: directory
        path: "/limx/src"
        owner: root
        group: root
        mode: 0755
    - name: mount nfs
      command: mount -t nfs 192.168.0.201:/limx/src /limx/src
